import '../../globals.css'

export const metadata = {
  title: 'h5 app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='h5'>{children}</div>
  )
}
