export const metadata = {
  title: 'post detail',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <div className='detail' style={{ width: "360px", margin: "0 auto", wordBreak: "break-all", overflow: "hidden" }}>
      {children}
    </div>
  )
}
